{% set name = "py-build-cmake" %}
{% set version = "0.3.0" %}
{% set python_min = "3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: dd605ebd18de74728bcc709b318a86e1f67e565e09bd3e6b40d835c434bc0c0f

build:
  number: 0
  entry_points:
    - py-build-cmake = py_build_cmake.cli:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - distlib >=0.3.5,<0.4.dev0
    - packaging >=23.2
    - pyproject-metadata >=0.7.1,<0.8.dev0
    - tomli >=1.2.3,<3
    - click >=8.1.7,<8.2.dev0
    - lark >=1.1.9,<2

test:
  imports:
    - py_build_cmake
  commands:
    - pip check
    - py-build-cmake --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/tttapa/py-build-cmake
  summary: PEP 517 compliant build backend for creating Python packages with cmake
  dev_url: https://github.com/tttapa/py-build-cmake
  doc_url: https://tttapa.github.io/py-build-cmake/
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ilya-lavrenov
