{% set name = "py-build-cmake" %}
{% set version = "0.2.0.dev20240805" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tttapa/py-build-cmake/archive/7ab73da351c7140f06d727a8705bece4cf544cd9.tar.gz
  sha256: 07ace2238fc8bf43b6dba891aa3e3019cd62d54a37463ff2a3902f628cce61ae

build:
  number: 0
  entry_points:
    - py-build-cmake = py_build_cmake.cli:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python >=3.7
    - pyproject-metadata >=0.7.1,<0.8.dev0
    - distlib >=0.3.5,<0.4.dev0
    - tomli >=1.2.3,<3
    - lark >=1.1.9,<2
    - pip
  run:
    - python >=3.7
    - pyproject-metadata >=0.7.1,<0.8.dev0
    - distlib >=0.3.5,<0.4.dev0
    - tomli >=1.2.3,<3
    - lark >=1.1.9,<2
    - click >=8.1.3,<8.2.dev0

test:
  imports:
    - py_build_cmake
  commands:
    - pip check
    - py-build-cmake --help
  requires:
    - pip

about:
  home: https://github.com/tttapa/py-build-cmake
  summary: PEP 517 compliant build backend for creating Python packages with cmake
  dev_url: https://github.com/tttapa/py-build-cmake
  doc_url: https://tttapa.github.io/py-build-cmake/
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ilya-lavrenov
